# Generated by Django 4.2.6 on 2023-10-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_songrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='status',
        ),
    ]
