# Generated by Django 4.2.6 on 2023-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_host_name_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
