# Generated by Django 4.1.7 on 2023-02-18 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("music_api", "0003_remove_song_genre_song_down_votes_song_up_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                (
                    "pin_code",
                    models.CharField(
                        default=management.models.generate_event_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[0-9A-Fa-f]+$"
                            )
                        ],
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.host"
                    ),
                ),
                ("queue", models.ManyToManyField(to="music_api.song")),
            ],
        ),
    ]
