# Generated by Django 4.1.7 on 2023-02-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="pin_code",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
    ]
