# Generated by Django 4.1.7 on 2023-02-19 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_event_pin_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="start_time",),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
