# Generated by Django 4.1.7 on 2023-02-19 21:10

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_event_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="pin_code",
            field=models.CharField(
                default=management.models.generate_event_code, max_length=8, unique=True
            ),
        ),
    ]
