# Generated by Django 4.1.7 on 2023-02-19 21:11

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_event_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="pin_code",
            field=models.CharField(
                default=management.models.generate_event_code,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
