# Generated by Django 4.1.7 on 2023-02-19 21:25

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_event_pin_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="qr_code",
            field=models.CharField(
                default=management.models.generate_qr_code,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
