# Generated by Django 4.1.7 on 2023-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                ("release_year", models.PositiveSmallIntegerField()),
                ("genre", models.CharField(max_length=255)),
                ("mood", models.CharField(max_length=255)),
                ("lyrics", models.TextField()),
                ("duration", models.DurationField()),
                ("audio_fingerprint", models.CharField(max_length=255)),
                ("album_art", models.URLField()),
            ],
        ),
    ]
