# Generated by Django 4.1.7 on 2023-02-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="audio_fingerprint",),
        migrations.RemoveField(model_name="song", name="duration",),
        migrations.RemoveField(model_name="song", name="lyrics",),
        migrations.RemoveField(model_name="song", name="mood",),
    ]
