# Generated by Django 4.1.7 on 2023-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "music_api",
            "0002_remove_song_audio_fingerprint_remove_song_duration_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="genre",),
        migrations.AddField(
            model_name="song",
            name="down_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="up_votes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
